# --- General Configuration ---

spring.application.name = S05T01
server.port = 8080

# --- MySQL ---

spring.r2dbc.url = r2dbc:mysql://localhost:3306/game
spring.r2dbc.username = root
spring.r2dbc.password = 123456789
spring.r2dbc.pool.enabled = true

# --- MongoDB ---

spring.data.mongodb.uri = mongodb://localhost:27017/game

# --- Others---

spring.autoconfigure.exclude = org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

