DROP TABLE if exist players;
CREATE TABLE players(
id VARCHAR(36) PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
score float NOT NULL,
connected BOOLEAN NOT NULL,
);

DROP TABLE if exists dealer;
CREATE TABLE dealer(
id VARCHAR(36) PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
connected BOOLEAN NOT NULL,
);